name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Deployment 👇
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.sha }}-public
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ${{ github.sha }}-public
