name: Build, Test and Deploy
on:
  push:
  #   branches:
  #     - main
  # pull_request:
  #   paths-ignore:
  #     - "**.md"
  #     - "**.bmpr"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js 🤖
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build --prefix-paths
          echo "pwd!!!!!!!!!!!!!!!!"
          pwd
          echo "ls!!!!!!!!!!!!"
          ls
          echo "specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/
          echo "another specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/valet.expert/
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint 🧶
        run: |
          echo "pwd!!!!!!!!!!!!!!!!"
          pwd
          echo "ls!!!!!!!!!!!!"
          ls
          echo "specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/
          echo "another specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/valet.expert/
          npm run lint

      - name: Cypress Test 🇨🇾
        run: |
          npm run cypress:ci
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Debug...
        run: |
          echo "pwd!!!!!!!!!!!!!!!!"
          pwd
          echo "ls!!!!!!!!!!!!"
          ls
          echo "specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/
          echo "another specific ls!!!!!"
          ls -la /home/runner/work/valet.expert/valet.expert/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public