name: Build, Test and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.bmpr"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build --prefix-paths

      - name: Lint 🧶
        run: |
          npm run lint

      - name: Test 🧪
        run: |
          npm run test -- --passWithNoTests

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
