name: Build, Test and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.bmpr"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js 🤖
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build --prefix-paths

      - name: Lint 🧶
        run: |
          npm run lint

      - name: Cypress Test 🇨🇾
        run: |
          npm run cypress:ci

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
